[build]
publish = "public"
command = "git submodule update --force --recursive --init --remote && hugo --gc --minify && hugo server"

[context.production.environment]
HUGO_VERSION = "0.80.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "git submodule update --force --recursive --init --remote && hugo --gc --minify --enableGitInfo && hugo server"

[context.split1.environment]
HUGO_VERSION = "0.80.0"
HUGO_ENV = "production"

[context.deploy-preview]
command = "git submodule update --force --recursive --init --remote && hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL && hugo server"

[context.deploy-preview.environment]
HUGO_VERSION = "0.80.0"

[context.branch-deploy]
command = "git submodule update --force --recursive --init --remote && hugo --gc --minify -b $DEPLOY_PRIME_URL && hugo server"

[context.branch-deploy.environment]
HUGO_VERSION = "0.80.0"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"
